### ISSUE TITLE
Image detection snippet

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/snippets#1]
It would be nice to run the https://github.com/SeaBee-no/seabee-ai on one image through the hub using cpu to understand the needed config. This will also make it easy for people to play with the detection and various models. Can for example run

```bash
nrseabee_det_preproc -c config/config_hub.yaml -o configs/nrseabee_det_preproc.yaml docker/test.yaml
nrseabee_det_test -c config/config_hub.yaml -o configs/nrseabee_det_test.yaml configs/nrseabee_det_preproc.yaml
nrseabee_det_postproc -c config/config_hub.yaml -o configs/nrseabee_det_postproc.yaml configs/nrseabee_det_test.yaml
```

**Comment by knl88** [comment]
@27am I made a small notebook, perhaps you can check fix it for running on https://hub-standard.seabee.sigma2.no, would just need to fix the paths I think, also, we would need to install the nrseabee code.

**Comment by knl88** [comment]
Perhaps we should just build nrseabee into the hub image @JamesSample ?

**Comment by knl88** [comment]
When we have added nrseabee it will be fun to test detecting some birds, for example on this mission https://geonode.seabee.sigma2.no/catalogue/#/detail/dataset/716

**Comment by JamesSample** [comment]
@knl88 @27am Sorry for being slow on this. I have just tried to rebuild the image, but getting errors from the `build-push` action. I have to head to a meeting now, but from a quick skim of the output I think it's because the `seabee-ai` repository is private, and the GitHub action doesn't have the necessary credentials for pip to be able to clone it. 

Running 

    pip install git+https://github.com/SeaBee-no/seabee-ai.git

from my Hub (where I have my Git credentials configured) seems to run OK.

Can we give the action credentials to install from private SeaBee repositories?

(And the SeaBee2 proposal is now submitted - fingers crossed!)

**Comment by knl88** [comment]
No worries, yep it is slightly unpractical with a private repo, but think the easiest workaround could be a build stage that uses the nrseabee docker image to build the python package into the hub image, then we can reuse credentials since we are logged into artifact registry. If that is difficult we can take a look at passing credentials. Private repos during build needs to use build secrets to pass the credentials to the docker build process. I can take a look on making a PR:)

**Comment by knl88** [comment]
Think the hub image with the nr detection works now, but we should probably give the hub a bit more resources.  Running on hub-standards can oom, hub-highmem seems to handle the memory requirements, but would benefit from a bit more cpu or a gpu. 

![image](https://github.com/SeaBee-no/snippets/assets/82077939/87c8cbe3-5cb3-4669-8104-21fe98bcccc5)

**Comment by knl88** [comment]
For reference the nrseabee build is setup [here](https://github.com/SeaBee-no/seabee-ai/commit/2039d33f4a0666e9bc567b85cb6888a409e041ee)
